### ISSUE TITLE
bundle installに--pathを付けるとテスト実行時にGemが見つけられない件

### ISSUE THREAD

**Issue by suiyujin** [jpmobile/jpmobile#102]
#### 起きた問題 :

`git clone`後に`bundle install --path vendor/bundle`の様にGemのインストール先をvendor/以下として実行しました。
そのため、`rake test`内の`rake db:migrate RAILS_ENV=test`の実行時にGemを見つけられない問題が発生しました。
#### エラー内容 :

```
/Users/ippe/.rbenv/versions/2.2.2/bin/ruby -S rake db:migrate RAILS_ENV=test
rake aborted!
`ActiveRecord::SessionStore` is extracted out of Rails into a gem. Please add `activerecord-session_store` to your Gemfile to use it.
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/configuration.rb:172:in `rescue in session_store'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/configuration.rb:169:in `session_store'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/default_middleware_stack.rb:47:in `block in build_stack'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/default_middleware_stack.rb:13:in `tap'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/default_middleware_stack.rb:13:in `build_stack'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:513:in `default_middleware_stack'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:501:in `app'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/test/rails/rails_root/config/environment.rb:5:in `<top (required)>'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:457:in `block in run_tasks_blocks'
NameError: uninitialized constant ActionDispatch::Session::ActiveRecordStore
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/configuration.rb:170:in `session_store'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/default_middleware_stack.rb:47:in `block in build_stack'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/default_middleware_stack.rb:13:in `tap'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/default_middleware_stack.rb:13:in `build_stack'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:513:in `default_middleware_stack'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:501:in `app'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/test/rails/rails_root/config/environment.rb:5:in `<top (required)>'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
/Users/ippe/sezemi/oss_hack_beginners/jpmobile/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:457:in `block in run_tasks_blocks'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [/Users/ippe/.rbenv/versions/2.2.2/bin/ruby...]
lib/tasks/jpmobile_tasks.rake:100:in `block (2 levels) in <top (required)>'
Tasks: TOP => test => test:rails
(See full trace by running task with --trace)
```
#### 解決策 :

`bundle install`時にパスを指定せず、Gemをローカルのrubyへインストールすることで問題なく実行できました。
#### 改善案 :

開発者向けのドキュメントを用意し、そちらに注意点として

> `bundle install`は--pathを付けずに実行してください

と記述すると良いと思うのですがいかがでしょうか。

**Comment by rust** [comment]
よさそう :+1:

**Comment by rust** [comment]
https://github.com/jpmobile/jpmobile/blob/main/CONTRIBUTING.md こちらに記載済み
