### ISSUE TITLE
rails-4-2ブランチ で NoMethodError: undefined method `to_crlf' for "":String 

### ISSUE THREAD

**Issue by jiikko** [jpmobile/jpmobile#127]
rails-4-2ブランチにて、テストが落ちてました。
`debian wheezy`の`ruby-2.2.2`と`ruby-2.3.1`で行いました。

```
  86) Jpmobile::Mail#receive Au From au iPhone should decode cp932-encoded mail correctly
      Failure/Error: @raw_source = value.to_crlf

      NoMethodError:
        undefined method `to_crlf' for #<String:0x00000002cb3b88>
        Did you mean?  to_c
      # ./lib/jpmobile/mail.rb:113:in `raw_source='
      # ./lib/jpmobile/mail.rb:84:in `init_with_string'
      # /home/deployer/.rvm/gems/ruby-2.3.1/gems/mail-2.6.4/lib/mail/message.rb:129:in `initialize'
      # /home/deployer/.rvm/gems/ruby-2.3.1/gems/mail-2.6.4/lib/mail/mail.rb:51:in `new'
      # /home/deployer/.rvm/gems/ruby-2.3.1/gems/mail-2.6.4/lib/mail/mail.rb:51:in `new'
      # ./spec/unit/receive_mail_spec.rb:319:in `block (4 levels) in <top (required)>'
```

ご確認よろしくお願いします。

**Comment by jiikko** [comment]
rails5で実行していたのでクローズします :sweat_drops: :bow: :sweat_drops:
```
$ bundle exec gem list | grep rails
rails (5.0.0.1)
```

同件で、https://github.com/jpmobile/jpmobile/pull/128 を作成しました。
ご確認よろしくお願いします :bow:
