### ISSUE TITLE
メールサーバが無いためテストが通らない

### ISSUE THREAD

**Issue by hoshitocat** [jpmobile/jpmobile#92]
### エラー内容

```
Failure/Error: expect {
       expected no Exception, got #<Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25> with backtrace:
         # ./vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
         # ./vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:2141:in `do_delivery'
         # ./vendor/bundle/ruby/2.1.0/gems/mail-2.6.3/lib/mail/message.rb:238:in `deliver'
         # ./spec/unit/mail_spec.rb:347:in `block (4 levels) in <top (required)>'
         # ./spec/unit/mail_spec.rb:346:in `block (3 levels) in <top (required)>'
```
### メソッドのモックを作成する

実際の送信処理は、ActionMailerが使われているためテストの本質ではない。したがって、このメソッドのモックを作成することで解決

**Comment by rust** [comment]
このテストはローカルホストで`postfix`などのメールサーバが動作していることが前提になっているので、確かに失敗します。

モックでもよいのですが、このspecの意味として、

* Ruby 1.9から導入された`Encoding`の変換がうまく動いて、SMTP通信するときにエラーにならないかどうか

ということを検証しているので、実はモックではなくメールサーバの方がいいと思っています。

**Comment by rust** [comment]
CI上で動くように変更済み
